site_name: LibreTiny
docs_dir: .

site_url: https://docs.libretiny.eu/
repo_url: https://github.com/kuba2k2/libretiny

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

plugins:
  - same-dir
  - mkdoxy:
      projects:
        # project names must be alphanumeric, else snippets won't work
        ltapi:
          src-dirs: cores/common/
          doxy-cfg:
            OPTIMIZE_OUTPUT_FOR_C: YES
            PREDEFINED: __cplusplus DOXYGEN=1
            CASE_SENSE_NAMES: NO
      save-api: .
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - include-markdown
  - search

extra_css:
  - docs/style.css

markdown_extensions:
  - md_in_html
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
