site_name: LibreTuya
docs_dir: .

site_url: https://docs.libretuya.ml/
repo_url: https://github.com/kuba2k2/libretuya

theme:
  name: material

plugins:
  - same-dir
  - mkdoxy:
      projects:
        # project names must be alphanumeric, else snippets won't work
        ltapi:
          src-dirs: arduino/libretuya/
          doxy-cfg:
            PREDEFINED: __cplusplus
            CASE_SENSE_NAMES: NO
        ltambz:
          src-dirs: arduino/realtek-ambz/
          doxy-cfg:
            PREDEFINED: __cplusplus
            CASE_SENSE_NAMES: NO
      save-api: .
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - include-markdown

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
